org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version_range=26.1.2.99

mod_id=essence
mod_name=Essence of Enchanting
mod_license=MIT
mod_version=0.1-NEOFORGE-26.1.2
mod_group_id=com.wdiscute
mod_authors=wdiscute
