modLoader="javafml" #mandatory

loaderVersion="[2,]" #mandatory

license="MIT"

issueTrackerURL="https://discord.gg/WsuFsGSegD" #optional

[[mods]] #mandatory
modId="essence"
version="${mod_version}"
displayName="${mod_name}"
displayURL="http://curseforge.com/minecraft/mc-mods/essence"
logoFile = "icon.png"
mod_authors="${mod_authors}" #optional
description='''A very enchanting mod'''

[[mixins]]
config="essence.mixins.json"

# In neoforge.mods.toml:
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.essence]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="${neo_version_range}" #mandatory
ordering="AFTER"
side="BOTH"

[[dependencies.essence]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="AFTER"
side="BOTH"